import React from 'react';
import * as LucideIcons from 'lucide-react';

// A mapping of icon names to Lucide components
export const ICONS: { [key: string]: React.ElementType } = {
  Activity: LucideIcons.Activity,
  Airplay: LucideIcons.Airplay,
  AlarmClock: LucideIcons.AlarmClock,
  Apple: LucideIcons.Apple,
  ArrowRightLeft: LucideIcons.ArrowRightLeft, // <-- Иконка перевода
  Award: LucideIcons.Award,
  Baby: LucideIcons.Baby,
  Banknote: LucideIcons.Banknote,
  BarChart: LucideIcons.BarChart,
  Bike: LucideIcons.Bike,
  Book: LucideIcons.Book,
  Briefcase: LucideIcons.Briefcase,
  Brush: LucideIcons.Brush,
  Bus: LucideIcons.Bus,
  Cake: LucideIcons.Cake,
  Camera: LucideIcons.Camera,
  Car: LucideIcons.Car,
  Cat: LucideIcons.Cat,
  Cigarette: LucideIcons.Cigarette,
  Clapperboard: LucideIcons.Clapperboard,
  Coffee: LucideIcons.Coffee,
  ConciergeBell: LucideIcons.ConciergeBell,
  Construction: LucideIcons.Construction,
  Dog: LucideIcons.Dog,
  DollarSign: LucideIcons.DollarSign,
  Dumbbell: LucideIcons.Dumbbell,
  Film: LucideIcons.Film,
  Fish: LucideIcons.Fish,
  Flag: LucideIcons.Flag,
  Gamepad2: LucideIcons.Gamepad2,
  Gift: LucideIcons.Gift,
  GraduationCap: LucideIcons.GraduationCap,
  Grape: LucideIcons.Grape,
  Hammer: LucideIcons.Hammer,
  Heart: LucideIcons.Heart,
  HeartPulse: LucideIcons.HeartPulse,
  Home: LucideIcons.Home,
  Laptop: LucideIcons.Laptop,
  Laugh: LucideIcons.Laugh,
  LayoutGrid: LucideIcons.LayoutGrid,
  Library: LucideIcons.Library,
  Lightbulb: LucideIcons.Lightbulb,
  Map: LucideIcons.Map,
  Medal: LucideIcons.Medal,
  Megaphone: LucideIcons.Megaphone,
  Mic: LucideIcons.Mic,
  Music: LucideIcons.Music,
  Paintbrush: LucideIcons.Paintbrush,
  Palette: LucideIcons.Palette,
  PawPrint: LucideIcons.PawPrint,
  PenTool: LucideIcons.PenTool,
  Phone: LucideIcons.Phone,
  PiggyBank: LucideIcons.PiggyBank,
  Plane: LucideIcons.Plane,
  Plug: LucideIcons.Plug,
  Plus: LucideIcons.Plus,
  Rocket: LucideIcons.Rocket,
  Scale: LucideIcons.Scale,
  School: LucideIcons.School,
  Settings: LucideIcons.Settings,
  Shield: LucideIcons.Shield,
  Shirt: LucideIcons.Shirt,
  ShoppingCart: LucideIcons.ShoppingCart,
  Sprout: LucideIcons.Sprout,
  Star: LucideIcons.Star,
  Store: LucideIcons.Store,
  Target: LucideIcons.Target,
  Ticket: LucideIcons.Ticket,
  Train: LucideIcons.Train,
  Trash: LucideIcons.Trash,
  TreePine: LucideIcons.TreePine,
  Trophy: LucideIcons.Trophy,
  Tv: LucideIcons.Tv,
  UtensilsCrossed: LucideIcons.UtensilsCrossed,
  Wallet: LucideIcons.Wallet,
  Wrench: LucideIcons.Wrench,
  Zap: LucideIcons.Zap,
};

// An array of the icon names for easy iteration in UI components
export const ICON_NAMES = Object.keys(ICONS).sort();